name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci
        run: make
        env:
          NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
      - name: coveralls
        if: success()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}